config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, :controllers => { registrations: 'registrations' }

  # # resources :users
  # # resources :devise
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "home#index"

  resources :book_lists do
    scope module: :book_lists do
      resources :reviews
    end
  end
  resources :books do
    scope module: :books do
      resources :book_lists
    end
  end
  # resources :clubs
  # resources :comments
  # resources :genres
  # resources :likes
  # resources :options
  # resources :polls
  # resources :posts
  # resources :reviews
  # resources :user_clubs
  resources :users do
    scope module: :users do
      resources :clubs
    end
  end

  resources :clubs do
    scope module: :clubs do
      resources :book_lists
      resources :user_clubs
      resources :posts do
        scope module: :posts do
          resources :comments
        end
      end
    end
  end

  # root to: redirect('/clubs')
root to: 'users#current_user_home'
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :admin, class_name: 'User'
end

app/controllers/clubs/book_lists_controller.rb
module Clubs
  class BookListsController < ApplicationController
    before_action :authenticate_user!

    def create
      @club = Club.find(params[:club_id])
      @book_list = BookList.new(book_list_params.merge(default_params))

      respond_to do |format|
        if @book_list.save
          format.html { redirect_to @club, notice: 'Book was added to the club.' }
        else
          format.html { redirect_to @club, notice: @book_list.errors.full_messages }
        end
      end
    end

    def update
      @club = Club.find(params[:club_id])
      @book_list = BookList.find(params[:id])

      respond_to do |format|
        if @book_list.update(book_list_params)
          format.html { redirect_to @club, notice: 'New Book was added to the club.' }
        else
          format.html { redirect_to @club, notice: @book_list.errors.full_messages }
        end
      end
    end

    private

      def book_list_params
        params.require(:book_list).permit(:book_id)
      end

      def default_params
        {
          ownerable: @club
        }
      end

  end
end

app/controllers/clubs/posts/comments_controller.rb
module Clubs
  module Posts
    class CommentsController < ApplicationController
      before_action :authenticate_user!
      before_action :set_comment, only: [:show, :edit, :update, :destroy]

      def create
        @club = Club.find(params[:club_id])
        @post = Post.find(params[:post_id])
        @comment = Comment.new(comment_params.merge(default_params))

        respond_to do |format|
          if @comment.save
            format.html { redirect_to @club, notice: 'Comment was successfully created.' }
          else
            format.html { redirect_to @club, notice: @comment.errors.full_messages }
          end
        end
      end

      def update
        @club = Club.find(params[:club_id])
        @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])

        respond_to do |format|
          if @comment.update(comment_params)
            format.html { redirect_to @club, notice: 'Comment was successfully updated.' }
          else
            format.html { redirect_to @club, notice: 'Error while updating comment.' }
          end
        end
      end

      private
        def set_comment
          @comment = Comment.find(params[:id])
        end

        def comment_params
          params.require(:comment).permit(:content)
        end

        def default_params
          {
            post: @post,
            user: current_user
          }
        end
    end
  end
end

app/controllers/clubs/posts_controller.rb
module Clubs
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def create
      @club = Club.find(params[:club_id])
      @post = Post.new(post_params.merge(default_params))

      respond_to do |format|
        if @post.save
          format.html { redirect_to @club, notice: 'Post was successfully created.' }
        else
          format.html { redirect_to @club, notice: 'Error while creating post.' }
        end
      end
    end

    def update
      @club = Club.find(params[:club_id])
      @post = Post.find(params[:id])

      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @club, notice: 'Post was successfully updated.' }
        else
          format.html { redirect_to @club, notice: 'Error while updating post.' }
        end
      end
    end

    def destroy
      @club = Club.find(params[:club_id])
      @post.destroy
      respond_to do |format|
        format.html { redirect_to @club, notice: 'Post was successfully destroyed.' }
      end
    end

    private
      def set_post
        @post = Post.find(params[:id])
      end

      def post_params
        params.require(:post).permit(:content, :club_id)
      end

      def default_params
        {
          club: @club,
          user: current_user
        }
      end
  end
end

app/controllers/clubs/user_clubs_controller.rb
module Clubs
  class UserClubsController < ApplicationController
    before_action :authenticate_user!

    def create
      @club = Club.find(params[:club_id])
      @user_club = UserClub.new(default_params)

      respond_to do |format|
        if @user_club.save
          format.html { redirect_to @club, notice: 'User sucessfully joined club.' }
        else
          format.html { redirect_to clubs_path, notice: @user_club.errors.full_messages }
        end
      end
    end

    private

      def default_params
        {
          club: @club,
          user: current_user
        }
      end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  def index
    @clubs = Club.all
    @new_user_joins_club = UserClub.new
  end

  def show
    @all_posts = Post.all
    @new_post = Post.new
    @new_comment = Comment.new
    @new_current_book = BookList.new
  end

  def new
    @club = Club.new
  end

  def edit
  end

  def create
    @club = Club.new(club_params.merge(default_params))

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_club
      @club = Club.find(params[:id])
    end

    def club_params
      params.require(:club).permit(:title, :description, :book_due_date)
    end

    def default_params
      {
        admin: current_user
      }
    end
end

app/controllers/users/clubs_controller.rb
module Users
  class ClubsController < ApplicationController
    before_action :authenticate_user!

    def index
      @clubs = Club.all
    end
  end
end

app/views/clubs/_admin_dropdown.html.erb
<div class="dropdown float-right">
  <button type="button" class="btn btn-icon btn-large btn-ghost ml-2 border" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= icon_tag "menu" %>
  </button>

  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="admin-actions">
    <%= link_to 'Edit Club', edit_club_path(@club), class: "dropdown-item" %>
    <% if UserClub.where(club: @club).count == 0 %>
      <%= link_to 'Destroy', @club, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
    <% end %>
  </div>
</div>

app/views/clubs/_book_card.html.erb
<div class="card mb-4 shadow-sm book-content">
  <div class="card-body">
    <% current_club_book_list_item = BookList.where(ownerable_type: "Club", ownerable_id: @club.id).last %>
    <% if current_club_book_list_item.nil? %>
      <% if current_user.is_admin_of_club?(@club) %>
        <h5 class="card-title"> Get started by adding a book! </h5>
        <div class="d-flex justify-content-between align-items-center">
          <%= form_for [@club,@new_current_book] do |f| %>
              <%= f.collection_select(:book_id, Book.all, :id, :title, {:prompt => "Choose Book"}, {:class=>'form-control', :onchange => 'this.form.submit()'}) %>
          <% end %>
        </div>
      <% else %>
      <h5 class="card-title"> There is no assigned book at the moment! </h5>
      <% end %>
    <% else %>
    <p class="lead">THE BOOK WE ARE READING</p>
      <%= image_tag current_club_book_list_item.book.picture_url, style:'height: 225px; width: 100%; display: block;'%>

      <div class="modal fade" id="editBookModal" tabindex="-1" role="dialog" aria-labelledby="editBookModalLabel" aria-hidden="true"></div>

      <h5 class="card-title"> <%= current_club_book_list_item.book.title %> </h5>
      <p>
        <strong>Author:</strong> <%= current_club_book_list_item.book.author %>
      </p>
      <p>
        <strong>Genre:</strong> <%= current_club_book_list_item.book.genre.name %>
      </p>
      <p>
        <strong>Length:</strong>  <%= current_club_book_list_item.book.pages %> pages
      </p>
      <p>
        <strong>Avg Rating:</strong> <%= pluralize(current_club_book_list_item.book.avgRating, "star") %>
      </p>

      <% if @club.book_due_date.nil? %>
        <% if current_user.is_admin_of_club?(@club) %>
          <div class="d-flex justify-content-between align-items-center">
            <%= form_for @club do |f| %>
              <div class="field">
                <%= f.label :book_due_date, 'Due Date:' %>
                <%= f.date_select :book_due_date %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p>
          <strong>Book due date:</strong>
          <%= @club.book_due_date %>
        </p>
      <% end %>
      <% if current_user.is_admin_of_club?(@club) %>
        <div class="d-flex justify-content-between align-items-center">
          <%= form_for [@club,current_club_book_list_item] do |f| %>
              <%= f.label :book_id, 'Change Book:' %>
              <%= f.collection_select(:book_id, Book.all, :id, :title, {:prompt => "Change Book"}, {:class=>'form-control', :onchange => 'this.form.submit()'}) %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<h1 class="display-4"><%= @club.title %></h1>
<p class="lead"><%= @club.description %></p>

<%= form_for @club do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Name of club' %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title'%>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description,class: 'form-control', placeholder: 'What is the club about..'%>
  </div>

  <%= f.submit "Update Club", class: 'float-right btn btn-light mt-1' %><br/>
<% end %>

app/views/clubs/index.html.erb
<%= link_to 'Open a Club', new_club_path, class: 'btn btn-primary btn-lg float-right' %>

<% if user_signed_in? %>
  <div class="card-columns">
    <% @clubs.each do |club| %>
        <div class="card text-center club-cards" style="width: 18rem;">
          <div class="card-body">
            <h3 class="card-title"> <%= club.title %> </h3>
            <p class="card-text">  <%= club.description %>  </p>
            <% if current_user.is_member_of_club?(club) || current_user.is_admin_of_club?(club) %>
              <div class="mb-3 mt-3"> <%= link_to 'Open', club,  class: 'btn btn-light' %> </div>
            <% else %>
              <%= form_for [club, @new_user_joins_club] do |f| %>
                <%= f.submit "Join Club", class: 'btn btn-primary' %><br/>
              <% end %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
<% end %>

app/views/clubs/new.html.erb
<h1>Create a New Club</h1>

<%= form_for @club do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Name of club' %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title'%>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description,class: 'form-control', placeholder: 'What is the club about..'%>
  </div>

  <%= f.submit "Create Club", class: 'float-right btn btn-light mt-1' %><br/>
<% end %>

app/views/clubs/show.html.erb
<% if current_user.belongs_to_club?(@club) %>
  <% if current_user.is_admin_of_club?(@club) %>
    <%= render 'admin_dropdown', club: @club %>
  <% end %>
  <h1 class="display-4"><%= @club.title %></h1>
  <p class="lead"><%= @club.description %></p>
  <div class="row">
    <div class="col-md-4 order-md-2 mb-4 p-0 container-sidebar">
      <%= render 'book_card', club: @club %>
    </div>
    <div class="col-md-8 order-md-1 container-body">
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <%= render 'clubs/posts/form_for_posts', club: @club, post: @new_post%>
        <div class="container">
          <h6 class="border-bottom border-gray pb-2 mb-0"> Recent Posts </h6>
          <%= render 'clubs/posts/show_posts' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h1>Seems like you tried to access a club that you are not a part of.</h1>
  <h2>Try joining a by going to 'Join a Club'</h2>
<% end %>