config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, :controllers => { registrations: 'registrations' }

  # # resources :users
  # # resources :devise
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "home#index"

  resources :book_lists do
    scope module: :book_lists do
      resources :reviews
    end
  end
  resources :books do
    scope module: :books do
      resources :book_lists
    end
  end
  # resources :clubs
  # resources :comments
  # resources :genres
  # resources :likes
  # resources :options
  # resources :polls
  # resources :posts
  # resources :reviews
  # resources :user_clubs
  resources :users do
    scope module: :users do
      resources :clubs
    end
  end

  resources :clubs do
    scope module: :clubs do
      resources :book_lists
      resources :user_clubs
      resources :posts do
        scope module: :posts do
          resources :comments
        end
      end
    end
  end

  # root to: redirect('/clubs')
root to: 'users#current_user_home'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  mount_uploader :picture, PictureUploader

  def avgRating
    sum = 0
    count = 0
    Review.where(book: self).find_each do |review|
      sum += review.stars
      count += 1
    end
    if count > 0
      return sum/count
    end
    return 0
  end

end

app/controllers/books/book_lists_controller.rb
module Books
  class BookListsController < ApplicationController
    before_action :authenticate_user!

    def show
    end

    def create
      @book = Book.find(params[:book_id])
      @book_list = BookList.new(book_list_params.merge(default_params))

      respond_to do |format|
        if @book_list.save
          format.html { redirect_to books_path, notice: 'Book was added to list created.' }
        else
          format.html { redirect_to books_path, notice: @book_list.errors.full_messages }
        end
      end
    end

    private

      def book_list_params
        params.require(:book_list).permit(:status)
      end

      def default_params
        {
          ownerable: current_user,
          book: @book,
          pages_read: 0
        }
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user_book_list = BookList.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def all_index
    @books = Book.all
  end

  def edit
    @edit_book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { redirect_to books_path, notice: 'Error creating book.' }
      end
    end
  end

  def update
    @edit_book = Book.find(params[:id])

    respond_to do |format|
      if @edit_book.update(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
      else
        format.html { redirect_to books_path, notice: 'Error updating book.' }
      end
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :genre_id, :pages, :picture)
  end
end

app/views/books/_edit_book_modal.html.erb
<div class="modal fade" id="<%= "edit-book-modal-"+book.id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="editBookModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header d-block">
        <div class="d-flex">
          <h5 class="modal-title" id="editBookModalLabel"> <%= book.title.upcase %> </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
      </div>
      <div class="modal-body">
        <%= form_for [book] do |f| %>
        <div class="form-group row">
          <%= f.label :title, 'Title', class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Book Title' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :author, 'Author', class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= f.text_field :author, class: 'form-control', placeholder: 'Author Name' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :pages, 'Pages', class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= f.number_field :pages, class: 'form-control', placeholder: '0' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :genre, 'Genre', class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {:prompt => "Choose One"}, {:class=>'form-control'}) %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :picture, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= f.file_field :picture, class: 'form-control custom-file-input', id:"customFile" %>
            <label class="custom-file-label form-control" for="customFile">Choose file</label>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "Save", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_new_book_modal.html.erb
<div class="modal fade" id="newBookModal" tabindex="-1" role="dialog" aria-labelledby="newBookModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newBookModalLabel">Add a new book</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for [book] do |f| %>
          <div class="form-group row">
            <%= f.label :title, 'Title', class: 'col-sm-2 col-form-label' %>
            <div class="col-sm-10">
              <%= f.text_field :title, class: 'form-control', placeholder: 'Book Title' %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :author, 'Author', class: 'col-sm-2 col-form-label' %>
            <div class="col-sm-10">
              <%= f.text_field :author, class: 'form-control', placeholder: 'Author Name' %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :pages, 'Pages', class: 'col-sm-2 col-form-label' %>
            <div class="col-sm-10">
              <%= f.number_field :pages, class: 'form-control', placeholder: '0' %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :genre, 'Genre', class: 'col-sm-2 col-form-label' %>
            <div class="col-sm-10">
              <%= f.collection_select(:genre_id, Genre.all, :id, :name, {:prompt => "Choose One"}, {:class=>'form-control'}) %>
            </div>
          </div>

          <div class="form-group row">
              <%= f.label :picture, class: 'col-sm-2 col-form-label' %>
              <div class="col-sm-10">
                <%= f.file_field :picture, class: 'form-control custom-file-input', id:"customFile" %>
                <label class="custom-file-label form-control" for="customFile">Choose file</label>
              </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Save", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/_show_book_modal.html.erb
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header d-block">
      <div class="d-flex">
        <h5 class="modal-title" id="showBookModalLabel"> <%= @book.title %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <h6 class="modal-title text-muted">By: <%= @book.author %> </h6>
    </div>
    <div class="modal-body">
      <div class="card flex-md-row mb-4 h-md-250 border-0">
        <%= image_tag @book.picture_url, class:'card-img-right flex-auto d-none d-lg-block', style:'width: 150px; height: 200px;'%>
        <div class="card-body d-flex flex-column align-items-start">
          <p>
            <strong>Genre:</strong> <%= @book.genre.name %>
          </p>
          <p>
            <strong>Length:</strong> <%= @book.pages %> pages
          </p>
          <p>
            <strong>Average Rating:</strong> <%= pluralize(@book.avgRating, "star") %>
          </p>
        </div>
      </div>
      <%= render 'show_book_reviews' %>
    </div>
  </div>
</div>

app/views/books/_show_book_reviews.html.erb
<div class="p-3 bg-white rounded">
  <h5 class="border-bottom border-gray pb-2 mb-0"> Reviews </h5>

  <% Review.where(book: @book).find_each do |review| %>
    <div class="media text-muted pt-1">
      <span alt="32x32" class="d-flex justify-content-center mr-2 rounded review-user-display" style="width: 32px; height: 32px;" data-holder-rendered="true">
        <%= review.user.user_initial %>
      </span>
      <p class="media-body pb-1 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark"><%= review.user.name || review.user.email %></strong>
        <%= pluralize(review.stars, "star") %>
      </p>
    </div>
  <% end %>
</div>

app/views/books/edit.js.erb
console.log("***************");
$('#editBookModal').html("<%= j render('/books/edit_book_modal')%>");
$('#editBookModal').modal('show');
console.log("................");

app/views/books/index.html.erb
<button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#newBookModal">
  Add a Book
</button>

<%= render 'new_book_modal', book: @book %>

<div class="row">
  <% @books.each do |book| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm book-content">
        <%= image_tag book.picture_url, style:'height: 225px; width: 100%; display: block;'%>
        <div class="card-body">
          <%= link_to edit_book_path(book), data: { toggle: "modal", target: "#edit-book-modal-"+book.id.to_s}, class: 'edit_book_modal_link btn btn-sm btn-outline-secondary edit-link' do %>
            <%= icon_tag "edit-icon" %>
          <% end %>
          <h5 class="card-title"> <%= book.title %> </h5>
          <p>
            <strong>Author:</strong> <%= book.author %>
          </p>
          <p>
            <strong>Genre:</strong> <%= book.genre.name %>
          </p>
          <p>
            <strong>Length:</strong>  <%= book.pages %> pages
          </p>
          <p>
            <strong>Avg Rating:</strong> <%= pluralize(book.avgRating, "star") %>
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <%= form_for [book,@user_book_list] do |f| %>
            <%= f.select(:status, [['Reading', '1'],['Wish List', '2'],['Done', '3']],
              {prompt: 'Add to List'}, {:class => 'form-control', :onchange => 'this.form.submit()' }) %>
            <% end %>
            <%= link_to "View", book_path(book), remote: true, class: 'show_book_modal_link btn btn-sm btn-outline-secondary'%>
            <div class="modal fade" id="showBookModal" tabindex="-1" role="dialog" aria-labelledby="showBookModalLabel" aria-hidden="true"></div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'edit_book_modal', book: book%>
  <% end %>
</div>

app/views/books/show.js.erb
$('#showBookModal').html("<%= j render('/books/show_book_modal')%>");
$('#showBookModal').modal('show');