config/routes.rb
Rails.application.routes.draw do

  # devise_for :users

  devise_for :users, :controllers => { registrations: 'registrations' }

  # # resources :users
  # # resources :devise
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "home#index"

  resources :book_lists do
    scope module: :book_lists do
      resources :reviews
    end
  end
  resources :books do
    scope module: :books do
      resources :book_lists
    end
  end
  # resources :clubs
  # resources :comments
  # resources :genres
  # resources :likes
  # resources :options
  # resources :polls
  # resources :posts
  # resources :reviews
  # resources :user_clubs
  resources :users do
    scope module: :users do
      resources :clubs
    end
  end

  resources :clubs do
    scope module: :clubs do
      resources :book_lists
      resources :user_clubs
      resources :posts do
        scope module: :posts do
          resources :comments
        end
      end
    end
  end

  # root to: redirect('/clubs')
root to: 'users#current_user_home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  mount_uploader :picture, PictureUploader

  def avgRating
    sum = 0
    count = 0
    Review.where(book: self).find_each do |review|
      sum += review.stars
      count += 1
    end
    if count > 0
      return sum/count
    end
    return 0
  end

end

app/models/book_list.rb
class BookList < ApplicationRecord
  belongs_to :book
  belongs_to :ownerable, polymorphic: true
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :admin, class_name: 'User'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :poll
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :club
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :club
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :book_lists, as: :ownerable

  def user_initial
    return initial_to_caps(name || email)
  end

  def initial_to_caps(username)
    username[0].upcase
  end

  def username
    if last_name.nil?
      return (name || email)
    elsif !name.nil?
      return name + " " + last_name
    end
    return email
  end

  def is_member_of_club?(club)
    return UserClub.where(user: self, club: club).any?
  end

  def is_admin_of_club?(club)
    return club.admin == self
  end

  def belongs_to_club?(club)
    return is_member_of_club?(club) || is_admin_of_club?(club)
  end
end

app/models/user_club.rb
class UserClub < ApplicationRecord
  belongs_to :user
  belongs_to :club
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_lists_controller.rb
class BookListsController < ApplicationController
  before_action :authenticate_user!

  def update
    @book_list = BookList.find(params[:id])
    respond_to do |format|
      updated_params = book_list_params
      if finished_book?
        updated_params = updated_params.merge(change_status_to_done)
      end
      if @book_list.update(updated_params)
        format.html { redirect_to user_path(current_user), notice: 'Book-List was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_list }
      else
        format.html { redirect_to user_path(current_user), notice: 'ERROR updating Book-List.' }
        format.json { render json: @book_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book_list = BookList.find(params[:id])
    @book_list.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Book was successfully removed from list.' }
      format.json { head :no_content }
    end
  end

  private

  def book_list_params
    params.require(:book_list).permit(:pages_read)
  end

  def finished_book?
    book_list_params[:pages_read].to_i >= @book_list.book.pages
  end

  def change_status_to_done
    {
      status: 3
    }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user_book_list = BookList.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def all_index
    @books = Book.all
  end

  def edit
    @edit_book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { redirect_to books_path, notice: 'Error creating book.' }
      end
    end
  end

  def update
    @edit_book = Book.find(params[:id])

    respond_to do |format|
      if @edit_book.update(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
      else
        format.html { redirect_to books_path, notice: 'Error updating book.' }
      end
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :genre_id, :pages, :picture)
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  def index
    @clubs = Club.all
    @new_user_joins_club = UserClub.new
  end

  def show
    @all_posts = Post.all
    @new_post = Post.new
    @new_comment = Comment.new
    @new_current_book = BookList.new
  end

  def new
    @club = Club.new
  end

  def edit
  end

  def create
    @club = Club.new(club_params.merge(default_params))

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_club
      @club = Club.find(params[:id])
    end

    def club_params
      params.require(:club).permit(:title, :description, :book_due_date)
    end

    def default_params
      {
        admin: current_user
      }
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @new_review = Review.new
  end

  def current_user_home
    redirect_to current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_tag(symbol, icon_modifier: nil)
    inline_svg "#{symbol}.svg", class: "icon inactive #{icon_modifier}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">BookClubsApp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to('My Profile', user_path(current_user), class: "nav-link")  %>
          </li>
          <li class="nav-item active">
            <%= link_to('My Clubs', user_clubs_path(current_user), class: "nav-link")  %>
          </li>
          <li class="nav-item active">
            <%= link_to('Join a Club', clubs_path, class: "nav-link")  %>
          </li>
          <li class="nav-item active">
            <%= link_to('Search all Books', books_path, class: "nav-link")  %>
          </li>
        </ul>
        <% end %>
        <span class="nav-item dropdown navbar-nav ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? %>
              <%= current_user.email %>
            <% else %>
              Welcome!
            <% end %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
            <%= link_to('Log Out', destroy_user_session_path, method: :delete, class: "dropdown-item") %>
            <% else %>
            <%= link_to('Log In', new_user_session_path, class: "dropdown-item")  %>
            <%= link_to('Sign Up', new_user_registration_path, class: "dropdown-item")  %>
            <% end %>
          </div>
        </span>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>